version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/lib/go"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "Workiva/service-platform"
    commit-message:
      prefix: "go-lib: "
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "Workiva/service-platform"
    commit-message:
      prefix: "go-tool: "
  - package-ecosystem: "maven"
    directory: "/lib/java"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "Workiva/service-platform"
    commit-message:
      prefix: "java-lib: "
  - package-ecosystem: "maven"
    directory: "/examples/java"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "Workiva/service-platform"
    commit-message:
      prefix: "java-exam: "
  - package-ecosystem: "gomod"
    directory: "/examples/go"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "Workiva/service-platform"
    commit-message:
      prefix: "go-exam: "
  - package-ecosystem: "maven"
    directory: "/test/integration/java/frugal-integration-test"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "Workiva/service-platform"
    commit-message:
      prefix: "java-test: "
  - package-ecosystem: "gomod"
    directory: "/test/integration"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "Workiva/service-platform"
    commit-message:
      prefix: "go-test: "
  - package-ecosystem: "pip"
    directory: "/lib/python"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "Workiva/service-platform"
    commit-message:
      prefix: "py-lib: "
